
language: cpp

env:
  global:
  - ExternalData_OBJECT_STORES="${HOME}/.ExternalData"
  - PROJ_SRC="${TRAVIS_BUILD_DIR}"
  - ITK_REPOSITORY_REMOTE="https://ITK.org/ITK.git"
  - ITK_REPOSITORY="${ExternalData_OBJECT_STORES}/ITK.git"
  - ITK_MODULE_NAME=SimpleITKFiltersModule
  - ITK_TAG=master
  - ITK_SRC="${HOME}/ITK"

cache:
  directories:
    - ${ExternalData_OBJECT_STORES}

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja $( command -V cmake &>2 /dev/null || echo "cmake" ); fi

before_script:
   - cmake --version
   - env
   - bash -x ${PROJ_SRC}/test/ci/CacheAndUpdateITK.sh

script:
   - ctest -V -S ${PROJ_SRC}/test/ci/dashboard.cmake
